//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pastephoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public int id { get; set; }
        public int id_pastephoto { get; set; }
        public string filename { get; set; }
        public string comment { get; set; }
        public string commented_by { get; set; }
        public Nullable<bool> selected { get; set; }
        public Nullable<int> rate { get; set; }
    
        public virtual pastephoto pastephoto { get; set; }
    }
}
